# Gradle 성능 설정
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Windows 파일 잠금 문제 해결
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configuration-cache=false

# Transforms 임시파일 이동 오류 우회
org.gradle.internal.transforms.max-retries=5

# Android 설정
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
